version: '3.1'

services:
  kandinsky-bot:
    build: ./kadinsky-bot
    image: kandinsky_bot
    container_name: kandinsky_bot
    ports:
      - "8090:8090"

  telegram-bot:
    build: ./telegram-bot
    image: telegram_bot
    container_name: telegram_bot
    ports:
      - "8070:8070"
    depends_on:
      - kandinsky-bot
      - telegram-bot-db
    environment:
      - SPRING_DATASOURCE_URL=
      - SPRING_DATASOURCE_USER=
      - SPRING_DATASOURCE_PASSWORD=
      - KANDINSKY_SERVER_HOST=
