version: '3.1'

services:
  kandinsky-bot:
    build: ./kadinsky-bot
    image: kandinsky_bot
    container_name: kandinsky_bot
    ports:
      - "8090:8090"

  telegram-bot:
    build: ./telegram-bot
    image: telegram_bot
    container_name: telegram_bot
    ports:
      - "8080:8080"
    depends_on:
      - kandinsky-bot
      - telegram-bot-db
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://telegram_bot_db/mg_parser
      - SPRING_DATASOURCE_USER=quadalus
      - SPRING_DATASOURCE_PASSWORD=pollka78
      - KANDINSKY_SERVER_HOST=http://kandinsky-bot:8090

  telegram-bot-db:
    image: postgres:14-alpine
    container_name: telegram_bot_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_DB=mg_parser
      - POSTGRES_USER=quadalus
      - POSTGRES_PASSWORD=pollka78