kandinsky:
  api:
    key: A5E3A599F4058B1D7B432220F61E1ED9
    secret: BF6C8DAA74B77E197FC0638B5E1CFDE2

    endpoint:
      url: https://api-key.fusionbrain.ai/
      style_url: cdn.fusionbrain.ai/static/styles/api
      status_path: /key/api/v1/text2image/status/
      service_available_path: /key/api/v1/text2image/availability
      generate_path: key/api/v1/text2image/run

    client:
      buffer_size: 5242880

server:
  port: 8090