server:
  port: 8080

bot:
  name:
  token:

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/public_db
    username:
    password:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true