--liquibase formatted sql

--changeset quadalus:1
CREATE TABLE IF NOT EXISTS good_morning_wishes
(
    id   INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    text VARCHAR NOT NULL
);
--rollback DROP TABLE good_morning_wishes;


--changeset quadalus:2
CREATE TABLE IF NOT EXISTS telegram_user
(
    chat_id    BIGINT PRIMARY KEY,
    username   VARCHAR NOT NULL,
    first_name VARCHAR NOT NULL,
    last_name  VARCHAR NOT NULL
);
--rollback DROP TABLE good_morning_wishes;
