spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    #docker
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USER}
    password: ${SPRING_DATASOURCE_PASSWORD}
    #local
    #    url: jdbc:postgresql://localhost:5432/********
    #    username: ******
    #    password: ******

    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true